<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Ticket</h1>

<form class="pure-form" method="post" action="/ticket/new">
    <label for="title">Title</label>
    <input name="title" id="title" type="text" size="60" /><br />

    <label for="description">Description</label>
    <textarea name="description" id="description" rows="6" cols="80"></textarea><br />

    <label for="component">Component</label>
    <select name="component">
        <option value=""></option>
<?php
foreach($components as $component): ?>
    <option value="<?=$component->getId()?>"><?=$component->getName()?></option>
<?php
endforeach;
?>
    </select><br />

    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>

<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>All Tickets</h1>

<p><a href="/ticket/new">Add new ticket</a></p>

<?php
if(count($tickets) > 0):
?>
<table class="pure-table">
    <tr>
        <th>Title</th>
        <th>Component</th>
        <th>Description</th>
        <th>Actions</th>
    </tr>

<?php
    $odd = true;
    foreach($tickets as $ticket): ?>

        <tr <?=$odd ? "class=\"pure-table-odd\"" : ""; ?>>
        <td><?=$ticket->getTitle() ?></td>
        <td><?=$ticket->getComponent() ?></td>
        <td><?=$ticket->getShortDescription() ?> ...</td>
        <td>
            <a href="<?=$router->pathFor('ticket-detail', ['id' => $ticket->getId()])?>">view</a>
        </td>
    </tr>

<?php
    $odd = $odd ? false : true;
    endforeach; ?>
</table>
<?php else: ?>
<p>No current tickets</p>
<?php endif; ?>

</body>
</html>
